bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -s escape-time 0
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g mouse on 
setw -g mode-keys vi

set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g history-limit 1000000     # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
# set -g status-position top # macOS / darwin style

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'

# ----------------------- Tui options -----------------------

# set -g status off

# set -g @plugin 'catppuccin/tmux'
# set -g @plugin 'tmux-plugins/tmux-battery'


# set -g @catppuccin_status_background "default"
# set -g @catppuccin_window_separator "a"
# 
# set -g @catppuccin_status_connect_separator "no"
# 
# set -g @catppuccin_status_justify "centre"
# 
# set -g @catppuccin_status_modules_right "application session"
# set -g @catppuccin_status_modules_left "battery"

run '~/.tmux/plugins/tpm/tpm'
